/**
 * AppSync Events のイベントタイプ定義
 */
export const BRAINWRITING_EVENT_TYPES = {
  USER_JOINED: "USER_JOINED",
  BRAINWRITING_STARTED: "BRAINWRITING_STARTED",
  SHEET_ROTATED: "SHEET_ROTATED",
} as const;

export type BrainwritingEventType =
  (typeof BRAINWRITING_EVENT_TYPES)[keyof typeof BRAINWRITING_EVENT_TYPES];

export const OSBORN_CHECKLIST_EVENT_TYPES = {
  AI_GENERATION_COMPLETED: "AI_GENERATION_COMPLETED",
  AI_GENERATION_FAILED: "AI_GENERATION_FAILED",
} as const;

export type OsbornChecklistEventType =
  (typeof OSBORN_CHECKLIST_EVENT_TYPES)[keyof typeof OSBORN_CHECKLIST_EVENT_TYPES];
